mp.add_key_binding("TAB", "show-time-info", function()
	local currentTime = os.date("%I:%M:%S", os.time())
	local remainingTime = mp.get_property("playtime-remaining")
	local endTime = os.date("%I:%M:%S", os.time() + remainingTime)
	local space = string.rep(" ", 140)
	mp.osd_message(string.format("🕛 Current time: %s %s 🕛 Ends at: %s", currentTime, space, endTime), 10)
end)
