#!/bin/env bash
if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]];then
  ~/.config/bspwm/monitor/monitor_connected
  pkill -f ~/.config/bspwm/monitor/monitor_auto_switch
  ~/.config/bspwm/monitor/monitor_auto_switch &
else
  pkill -f ~/.config/bspwm/monitor/monitor_auto_switch
  ~/.config/bspwm/monitor/monitor_auto_switch &
  ~/.config/bspwm/monitor/monitor_disconnected
fi
