#!/bin/bash
bspc desktop 1 --to-monitor HDMI-1-0
bspc desktop 2 --to-monitor HDMI-1-0
bspc desktop 3 --to-monitor HDMI-1-0
bspc desktop 4 --to-monitor HDMI-1-0
bspc desktop 5 --to-monitor HDMI-1-0
bspc desktop 6 --to-monitor HDMI-1-0
bspc desktop 7 --to-monitor HDMI-1-0
bspc desktop 8 --to-monitor HDMI-1-0
xrandr --output eDP-1 --off \
       --output HDMI-1-0 --auto --primary --rotate normal
bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8
bspc monitor eDP-1 -r
sh ~/.fehbg &
killall polybar
polybar bspwm-external &
