#!/bin/env bash
bspc desktop 1 --to-monitor eDP-1
bspc desktop 2 --to-monitor eDP-1
bspc desktop 3 --to-monitor eDP-1
bspc desktop 4 --to-monitor eDP-1
bspc desktop 5 --to-monitor eDP-1
bspc desktop 6 --to-monitor eDP-1
bspc desktop 7 --to-monitor eDP-1
bspc desktop 8 --to-monitor eDP-1
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal \
       --output HDMI-1-0 --off
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-1-0 -r
sh ~/.fehbg &
sh ~/.local/bin/auto_sleep &
killall polybar 
polybar bspwm-top-main &
