#!/bin/env bash
xrandr --output eDP-1 --primary --mode 1920x1080 -r 144.00 --rotate normal --output HDMI-1-0 --mode 1366x768 -r 75.00 --rotate normal --right-of eDP-1
bspc monitor eDP-1 -d 1
bspc monitor HDMI-1-0 -d 2 3 4 5 6 7 8 9 
bspc desktop 2 --to-monitor HDMI-1-0
bspc desktop 3 --to-monitor HDMI-1-0
bspc desktop 4 --to-monitor HDMI-1-0
bspc desktop 5 --to-monitor HDMI-1-0
bspc desktop 6 --to-monitor HDMI-1-0
bspc desktop 7 --to-monitor HDMI-1-0
bspc desktop 8 --to-monitor HDMI-1-0
bspc desktop 9 --to-monitor HDMI-1-0
bspc desktop Desktop --remove
sh ~/.fehbg 
sh ~/.local/bin/switch-output/switched-analog
killall redshift
redshift &
$HOME/.config/polybar/launch.sh &
/opt/urserver/urserver-stop
