#!/bin/bash

# Configure display outputs
xrandr --output eDP-1 --auto --rotate normal --primary \
       --output HDMI-1-0 --auto --rotate normal --primary --left-of eDP-1

# Restart Polybar
killall polybar
polybar bspwm-top-main &
polybar bspwm-external &
sleep 2

bspc desktop 1 --to-monitor HDMI-1-0 --follow
bspc desktop 2 --to-monitor HDMI-1-0 --follow
bspc desktop 3 --to-monitor HDMI-1-0 --follow
bspc desktop 4 --to-monitor HDMI-1-0 --follow
bspc desktop 5 --to-monitor HDMI-1-0 --follow
bspc desktop 6 --to-monitor HDMI-1-0 --follow
bspc desktop 7 --to-monitor HDMI-1-0 --follow
bspc desktop 8 --to-monitor eDP-1 --follow

# Assign workspaces to monitors
bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7
bspc monitor eDP-1 -d 8

# Set wallpaper
~/.fehbg &
