#!/bin/env bash
xrandr --output eDP-1 --off --output HDMI-1-0 --mode 1920x1080 -r 60.00 --primary --rotate normal 
bspc desktop 1 --to-monitor HDMI-1-0
bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8 9 
bspc monitor eDP-1 -r
sh ~/.fehbg 
killall polybar conky redshift 
sh ~/.local/bin/urserver 
sh ~/.local/bin/switch-output/switched-hdmi 
polybar bspwm-external &
