#!/bin/env bash
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --off
killall polybar
polybar bspwm-top-main &&
bspc desktop 1 -m eDP-1 --follow
bspc desktop 2 -m eDP-1 --follow
bspc desktop 3 -m eDP-1 --follow
bspc desktop 4 -m eDP-1 --follow
bspc desktop 5 -m eDP-1 --follow
bspc desktop 6 -m eDP-1 --follow
bspc desktop 7 -m eDP-1 --follow
bspc desktop 8 -m eDP-1 --follow
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-1-0 -r
sh ~/.fehbg &
killall polybar
polybar bspwm-top-main &
sh ~/.local/bin/auto_sleep &
