; Global settings for redshift
[redshift]
temp-day=5700
temp-night=4000

fade=1


	dawn-time=6:00-7:45
	dusk-time=17:00-17:35

	brightness-day=1.0
	brightness-night=0.9
	gamma=0.8

; The location provider settings are in a different section.
;location-provider=manual

adjustment-method=randr

[manual]
;lat=
;lon=

