#!/bin/env bash

# Kill if already running
killall -9 xsettingsd picom sxhkd dunst xfce4-power-manager bspc polybar redshift nitrogen copyq xidlehook mpd musinify-mpd nm-applet 
# picom -b --experimental-backends &
# nm-applet &
# nitrogen --restore &
#xsetroot -cursor_name left_ptr &
# $HOME/.config/polybar/launch.sh &
#xsettingsd --config="~/.config/bspwm/xsettingsd" &
# --recursive /mnt/Files/0Linux/Pictures/Wallpaper/ --randomize --image-bg --interval 3600 &
#xhost + &
# xset led 3 &
xset b off 
sxhkd -c &
redshift &
$HOME/.config/bspwm/monitor/monitor 
numlockx on &
exec mpd &
dunst &
musnify-mpd &
/usr/lib/xfce-polkit/xfce-polkit &
"/opt/xdman/xdm-app" --background &
copyq &
$HOME/.local/bin/auto_lock &
# Start bspwm scripts
bspwinmask &

