#!/bin/env bash
bspc config border_width         3
bspc config window_gap           10

# bspc monitor HDMI-1-0 -d 5 6 7 8 
# bspc monitor eDP-1 -d 1 2 3 4 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# bspc config focused_border_color "#c099ff"
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#1E222A"
##Desktop 1
bspc rule -a Brave-browser desktop='^1' state=tiled follow=on
bspc rule -a firefox desktop='^1' state=tiled follow=on
##Desktop 2
bspc rule -a Thunar		   desktop='^2' follow=on   focus=on
bspc rule -a Xdm-app  desktop='^2' state=floating follow=on   focus=on sticky=off
##Desktop 3
bspc rule -a kitty	       desktop='^3'  state=tiled follow=on focus=on 
##Desktop 4
bspc rule -a Alacritty	   desktop='^4'  state=tiled follow=on focus=on 
bspc rule -a VSCodium      desktop='^4' state=tiled follow=on
bspc rule -a Geany  	   desktop='^4' state=tiled follow=on
##Desktop 5
bspc rule -a Zathura       desktop='^5' state=tiled follow=on
bspc rule -a copyq  	   desktop='^5' state=tiled follow=on
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done
##Desktop 6
bspc rule -a 'Microsoft Teams - Preview' desktop='^6' state=tiled follow=on
bspc rule -a ViberPC       desktop='^6' follow=on 
bspc rule -a discord       desktop='^6' state=tiled follow=on
bspc rule -a Steam         desktop='^6' state=tiled follow=off
##Desktop 7
bspc rule -a 'Jellyfin Media Player'  desktop='^7' state=tiled follow=on
bspc rule -a thunderbird   desktop='^7' follow=on
bspc rule -a Virt-manager  desktop='^7' follow=on
bspc rule -a VirtualBox    desktop='^7' state=tiled follow=on
bspc rule -a qBittorrent   desktop='^7' state=tiled follow=on
##Desktop 8
bspc rule -a Audacity   desktop='^8' 
bspc rule -a kdenlive desktop='^8' 
bspc rule -a Gimp   desktop='^8' state=tiled follow=on
##Floating Windows
bspc rule -a mpv --player-operation-mode=pseudo-gui state=floating sticky=on
bspc rule -a scrcpy        state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a Sxiv 		   state=floating
bspc rule -a Gpick         state=floating follow=on
bspc rule -a Ulauncher     state=floating follow=on
bspc rule -a Lxappearance  state=floating follow=on
bspc rule -a openrgb       state=floating follow=on
bspc rule -a Piper         state=floating follow=on
bspc rule -a Pavucontrol   state=floating follow=on
bspc rule -a alacritty-float state=floating follow=on
## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"
$HOME/.config/bspwm/autostart

