;    _______ _______  ___    ___ ___ _______  _______  _______
;   |   _   |   _   ||   |  |   Y   |   _   \|   _   ||   _   \
;   |.  1   |.  |   ||.  |  |   1   |.  1   /|.  1   ||.  l   /
;   |.  ____|.  |   ||.  |___\_   _/|.  _   \|.  _   ||.  _   1
;   |:  |   |:  1   ||:  1   ||:  | |:  1    \:  |   ||:  |   |
;   |::.|   |::.. . ||::.. . ||::.| |::.. .  /::.|:. ||::.|:. |
;   `---'   `-------'`-------'`---' `-------'`--- ---'`--- ---'
;    current bars{
;                  BSPWM }

[colors]
#background = ${xrdb:background}
background-alt = #2b2f37
background = #1e222a
foreground = #adb1b9

color0 = ${xrdb:color0}
color1 = ${xrdb:color1}
color2 = ${xrdb:color2}
color3 = ${xrdb:color3}
color4 = ${xrdb:color4}
color5 = ${xrdb:color5}
color6 = ${xrdb:color6}
color7 = ${xrdb:color7}
color8 = ${xrdb:color8}
color9 = ${xrdb:color9}
color10 = ${xrdb:color10}
color11 = ${xrdb:color11}
color12 = ${xrdb:color12}
color13 = ${xrdb:color13}
color14 = ${xrdb:color14}
color15 = ${xrdb:color15}
dark-light = #1b1e23
active-light = #313435
mauve = #cba6f7
disabled = ${xrdb:color0}


[bar/bspwm]
width =  100%
height = 24
padding-left =0
padding-right = 1
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-radius = 12
border-top-color = ${colors.background}
border-bottom-color = ${colors.background}

# Tray Settings
tray-position = right
tray-padding = 2
tray-background = #2b2f37
tray-maxsize = 24
tray-detached = false

line-size = 2
wm-restack = bspwm
scroll-up = brightnessctl set 2%+
scroll-down = brightnessctl set 2%-

modules-left =  round-left menu round-right  round-left xworkspaces round-right  round-left wifi-list round-left mpd round-right round-right  round-left  wired-network round-right round-left wlan round-right
modules-center =  round-left date round-right
modules-right =  round-left pulseaudio xbacklight round-right  round-left cpu round-right  round-left mem round-right round-left battery round-right  powermenu sep

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=12;4
font-1 = JetBrainsMono Nerd Font:size=12;3
font-2 = Material Design Icons:style=Bold:size=12;2
font-3 = unifont:fontformat=truetype:size=12:antialias=true;

enable-ipc = true
pseudo-transparency = false
cursor-click = pointer

[module/sep]
type = custom/text
content = " "
content-background = ${colors.background}
content-foreground = ${colors.background}
content-padding = 0

[module/round-left]
type = custom/text
content = %{T3}%{T-}
content-foreground = #2b2f37

[module/round-right]
type = custom/text
content = %{T3}%{T-}
content-foreground = #2b2f37

[module/menu]
type = custom/text
content = 
content-padding = 1
content-background = #2b2f37
content-foreground = #e5c07b
click-left = ~/.config/rofi/launcher/launcher
click-right = ~/.config/rofi/bin/windows

[module/xworkspaces]
type = internal/bspwm

pin-workspaces = true
inline-mode = true
enable-click = true
enable-scroll = true
reverse-scroll = false

format = <label-state>

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;

label-separator = ""
label-separator-background = #2b2f37

label-focused = %icon%
label-focused-foreground =  #00FF00
#label-focused-underline =  #00FF00
label-focused-padding = 1.0
label-focused-background = #2b2f37

label-occupied = %icon%
label-occupied-foreground =#ff9b93
label-occupied-background = #2b2f37
label-occupied-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 1
label-empty-background = #2b2f37


label-urgent = %icon%
label-urgent-foreground =  ${colors.foreground}
label-urgent-background = #2b2f37
label-urgent-padding = 1

scroll-up = brightnessctl set 2%+
scroll-down = brightnessctl set 2%-

[module/date]
type = internal/date
interval = 1

date =  %I:%M:%S %p
date-alt =  %A, %d %B %Y

# format = 🕓 <label>
label = %date%
format-foreground = #00D1FF
format-background = #2b2f37

[module/mem]
type = custom/script
exec = free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p'
format = <label>
format-prefix = "﬙ "
label = %output% MB
label-padding = 1
format-prefix-foreground = #90EE90
format-prefix-background = #2b2f37
label-foreground = #ADD8E6
label-background = #2b2f37
click-left= alacritty -e htop

[module/powermenu]
type = custom/text
content =" "
content-padding = 1
click-left = ~/.config/rofi/powermenu/powermenu &
content-foreground =  #e06c75
click-right=alacritty -e xkill

[module/wifi-list]
type = custom/text
content =" "
content-padding = 1
content-background = #2b2f37
content-foreground = #FFFFFF
click-left = networkmanager_dmenu &
click-right = gnome-clocks &

[module/wired-network]
type = internal/network
interface = enp3s0
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected =  %{F#98c379}  %downspeed% %{F#e06c75}  %upspeed%
format-connected-foreground = #90EE90
format-connected-background = #2b2f37
label-disconnected = 
format-disconnected-foreground = #e06c75
format-disconnected-background = #2b2f37

[module/wlan]
type = internal/network
interface = wlp4s0
interval = 2.0
format-connected =  <label-connected>
format-disconnected = <label-disconnected>
label-connected = 直 %{F#98c379}  %downspeed% %{F#e06c75}  %upspeed%
label-connected-foreground = #90EE90
format-connected-background = #2b2f37
label-disconnected = 睊
format-disconnected-foreground = #e06c75
format-disconnected-background = #2b2f37


[module/xbacklight]
type = internal/backlight
card = amdgpu_bl0
format = <ramp> <label>
format-background = #2b2f37
format-foreground = #90EE90
format-padding = 1
label = %percentage%%
ramp-0 = 
ramp-1 = 
ramp-2 = 

[module/cpu]
type = internal/cpu
interval = 2.5

format-prefix = "  "
format = <label>

label = CPU %percentage%%

format-background = #2b2f37
format-foreground = #DA6E8B


label-foreground = ${colors.color6}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = #e5c07b
format-volume-prefix-background = #2b2f37

format-volume = <label-volume>

label-volume = %percentage%%
label-volume-background = #2b2f37
label-volume-foreground = #e5c07b

label-muted =  muted
label-muted-foreground = ${colors.red}
label-muted-background = #2b2f37

click-right = pavucontrol

[module/battery]
type = internal/battery
battery = BAT1
adapter = AC0
full-at = 99
poll-interval = 2.5
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
label-charging =  %percentage%% %time%
label-charging-foreground = #ff9b93
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%% %time%
label-discharging-foreground = #ff9b93
format-full = <ramp-capacity> <label-full>
format-full-prefix =
format-full-prefix-foreground = #ff9b93
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-foreground = ${colors.foreground-alt}
animation-charging-0 = "  "
animation-charging-1 = "  "
animation-charging-2 = "  "
animation-charging-3 = "  "
animation-charging-4 = "  "
animation-charging-foreground = ${colors.foreground}
animation-charging-framerate = 750

[module/mpd]
type = internal/mpd
format-online = "<icon-prev> <toggle> <icon-next>"
format-offline = "offline"
format-underline = #FF00DB
icon-prev = 
icon-prev-padding = 1
icon-prev-foreground = #e5c07b
icon-play-prefix = #f00
icon-play = 
icon-play-padding = 1
icon-play-foreground = #e06c75
icon-pause = 
icon-pause-foreground = #ADD8E6
icon-pause-padding = 1
icon-next = 
icon-next-padding = 1
icon-next-foreground = #e5c07b
label-song = %title%
format-online-background = #2b2f37
format-offline-background = #2b2f37


[module/bspmode]
type = internal/bspwm

format = <label-mode>
pin-workspace = false
enable-scroll = false
inline-mode = false

;format-suffix = %{Fcolors.shade7}|%{F-}
format-background = ${colors.shade16}
format-foreground = ${colors.shade1}
;format-padding = 1


label-fullscreen-overline = ${colors.background}
label-floating-overline = ${colors.background}
label-pseudotiled-overline = ${colors.background}
label-locked-overline = ${colors.background}
label-sticky-overline = ${colors.background}
label-private-overline = ${colors.background}
label-marked-overline = ${colors.background}

label-fullscreen-underline = ${colors.background}
label-floating-underline = ${colors.background}
label-pseudotiled-underline = ${colors.background}
label-locked-underline = ${colors.background}
label-sticky-underline = ${colors.background}
label-private-unerline = ${colors.background}
label-marked-underline = ${colors.background}

label-fullscreen = 
label-fullscreen-padding-left = 1
label-floating = 
label-floating-padding-left = 1
label-pseudotiled = 
label-pseudotiled-padding-left = 1
label-locked = 
label-locked-padding-left = 1
label-sticky = 
label-sticky-padding-left = 1
label-private = 
label-private-padding-left = 1
label-marked = 
label-marked-padding-left = 1

[module/bsplayout]
type = internal/bspwm

format = <label-mode>
pin-workspace = false
enable-scroll = false
inline-mode = false

label-monocle-overline = ${colors.background}
label-tiled-overline = ${colors.background}
label-monocle-underline = ${colors.background}
label-tiled-underline = ${colors.background}

;format-suffix = %{Fcolors.shade7}|%{F-}
format-background = ${colors.shade16}
format-foreground = ${colors.shade1}
;format-padding = 1

; The following labels will be used to indicate the layout/mode
; for the focused workspace. Requires <label-mode>
;
; Available tokens:
;   None
label-monocle = 
;label-monocle-padding = 1
label-tiled = 
;label-tiled-padding = 1


[module/dunst]
type = custom/ipc
initial = 1
format-foreground = ${colors.shade3}
format-background = ${colors.shade16}
format-overline = ${colors.background}
format-underline = ${colors.background}
;format-padding = 1

hook-0 = echo "%{A1:notify-send "dunstctl set-paused toggle" && polybar-msg hook dunst 2:}  %{A}" &
hook-1 = echo "%{A1:notify-send "dunstctl set-paused toggle" && polybar-msg hook dunst 1:}  %{A}" &
